// <auto-generated />
using System;
using DatabaseProxy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseProxy.Migrations
{
    [DbContext(typeof(DatabaseProxy))]
    [Migration("20260401221950_Init_Db_2")]
    partial class Init_Db_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseProxy.EntityDependantProxy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("EntityProxyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("EntityProxyId");

                    b.ToTable("EntityDependantProxies");
                });

            modelBuilder.Entity("DatabaseProxy.EntityDependencyProxy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("EntityDependencyProxies");
                });

            modelBuilder.Entity("DatabaseProxy.EntityProxy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("EntityDependencyProxyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("EntityDependencyProxyId");

                    b.ToTable("EntityProxies");
                });

            modelBuilder.Entity("DatabaseProxy.EntityDependantProxy", b =>
                {
                    b.HasOne("DatabaseProxy.EntityProxy", null)
                        .WithMany("Dependants")
                        .HasForeignKey("EntityProxyId");
                });

            modelBuilder.Entity("DatabaseProxy.EntityProxy", b =>
                {
                    b.HasOne("DatabaseProxy.EntityDependencyProxy", null)
                        .WithMany("Dependants")
                        .HasForeignKey("EntityDependencyProxyId");
                });

            modelBuilder.Entity("DatabaseProxy.EntityDependencyProxy", b =>
                {
                    b.Navigation("Dependants");
                });

            modelBuilder.Entity("DatabaseProxy.EntityProxy", b =>
                {
                    b.Navigation("Dependants");
                });
#pragma warning restore 612, 618
        }
    }
}
