// <auto-generated />
using System;
using DatabaseProxy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseProxy.Migrations
{
    [DbContext(typeof(DatabaseProxy))]
    [Migration("20260507000851_standarized db for proxies 2")]
    partial class standarizeddbforproxies2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseProxy.Entities.EntityDependantProxy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("EntityProxyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EntityProxyShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("EntityProxy");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("EntityProxyId");

                    b.HasIndex("EntityProxyShadow")
                        .IsUnique()
                        .HasFilter("[EntityProxy] IS NOT NULL");

                    b.ToTable("EntityDependantProxies");
                });

            modelBuilder.Entity("DatabaseProxy.Entities.EntityDependencyProxy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("EntityDependencyProxies");
                });

            modelBuilder.Entity("DatabaseProxy.Entities.EntityProxy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("EntityDependencyProxyShadow")
                        .HasColumnType("bigint")
                        .HasColumnName("EntityDependencyProxy");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("EntityDependencyProxyShadow");

                    b.ToTable("EntityProxies");
                });

            modelBuilder.Entity("DatabaseProxy.Entities.EntityDependantProxy", b =>
                {
                    b.HasOne("DatabaseProxy.Entities.EntityProxy", null)
                        .WithMany("EntityDependantProxies")
                        .HasForeignKey("EntityProxyId");

                    b.HasOne("DatabaseProxy.Entities.EntityProxy", "EntityProxy")
                        .WithOne()
                        .HasForeignKey("DatabaseProxy.Entities.EntityDependantProxy", "EntityProxyShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EntityProxy");
                });

            modelBuilder.Entity("DatabaseProxy.Entities.EntityProxy", b =>
                {
                    b.HasOne("DatabaseProxy.Entities.EntityDependencyProxy", "EntityDependencyProxy")
                        .WithMany("EntityProxies")
                        .HasForeignKey("EntityDependencyProxyShadow")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EntityDependencyProxy");
                });

            modelBuilder.Entity("DatabaseProxy.Entities.EntityDependencyProxy", b =>
                {
                    b.Navigation("EntityProxies");
                });

            modelBuilder.Entity("DatabaseProxy.Entities.EntityProxy", b =>
                {
                    b.Navigation("EntityDependantProxies");
                });
#pragma warning restore 612, 618
        }
    }
}
